---
- name: Llamar API de AWX
  hosts: localhost
  vars:
    token: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
  tasks:
    - name: Inventarios AWX
      uri:
        url: "http://192.168.123.100:30080/api/v2/jobs"
        method: GET
        headers:
          Authorization: Bearer {{ token }}
      register: numero_de_paginas
      run_once: true
      delegate_to: localhost


    - name: numero de paginas
      run_once: true
      debug:
        msg: "{{ numero_de_paginas.count }}"
