---
- name: Llamar API de AWX
  hosts: localhost
  vars:
    token: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
  tasks:
    - name: Inventarios AWX
      uri:
        url: "http://192.168.123.100:30080/api/v2/jobs/?page_size=10&status=running"
        method: GET
        headers:
          Authorization: Bearer {{ token }}
      register: numero_de_paginas_get
      run_once: true
      delegate_to: localhost


    - name: Paginas encontradas
      run_once: true
      set_fact:
        numero_de_paginas: "{{ ((numero_de_paginas_get.json.count / 10) | round(0, 'ceil')) | int }}"

