- hosts: localhost
  tasks:
    - command: echo hola
      register: resultado

- hosts: all
  tasks:
  - name: Pruebas
    block: 


    - name: Variable
      set_fact:
        variable: {{ hostvars['localhost']['resultado'] }}
    
    - debug:
        var: variable
