---
- name: Llamar API de AWX
  hosts: localhost
  vars:
    token: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
  tasks:

  - name: Play 1
    hosts: localhost
    tasks:
      - set_fact:
          dato: "hola"
  
  
  - name: Play 2
    hosts: all
    tasks:
      - debug:
          var: dato
